
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '04D2907C95C5A3349BF508660B498B28'
    
_lr_action_items = {'AND':([1,5,11,12,16,17,18,],[-6,8,-5,-4,-2,-3,-1,]),'IMPLIES':([1,5,11,12,16,17,18,],[-6,9,-5,-4,-2,-3,-1,]),'NAME':([0,2,4,6,8,9,10,],[1,1,1,1,1,1,1,]),'CB':([1,7,11,12,13,14,15,16,17,18,],[-6,12,-5,-4,16,17,18,-2,-3,-1,]),'OB':([0,1,2,4,6,8,9,10,],[2,4,2,2,2,2,2,2,]),'COMMA':([1,3,5,7,11,12,13,14,15,16,17,18,],[-6,6,6,6,6,-4,6,6,6,-2,-3,-1,]),'OR':([1,5,11,12,16,17,18,],[-6,10,-5,-4,-2,-3,-1,]),'$end':([1,3,11,12,16,17,18,],[-6,0,-5,-4,-2,-3,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,4,6,8,9,10,],[3,5,7,11,13,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> OB expression OR expression CB','expression',5,'p_expression','parse.py',20),
  ('expression -> OB expression AND expression CB','expression',5,'p_expression','parse.py',21),
  ('expression -> OB expression IMPLIES expression CB','expression',5,'p_expression','parse.py',22),
  ('expression -> NAME OB expression CB','expression',4,'p_predicate','parse.py',32),
  ('expression -> expression COMMA expression','expression',3,'p_arguments','parse.py',38),
  ('expression -> NAME','expression',1,'p_name','parse.py',46),
]
